<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVoocpgf\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVoocpgf/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerVoocpgf.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerVoocpgf\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerVoocpgf\appProdProjectContainer([
    'container.build_hash' => 'Voocpgf',
    'container.build_id' => 'd0808052',
    'container.build_time' => 1594320961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVoocpgf');
