<?php

class WpkColocoPetsModuleFrontController extends ModuleFrontController
{
    public function init()
    {
        if (!$this->context->customer->isLogged()) {
            Tools::redirect(__PS_BASE_URI__);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function initContent()
    {
        parent::initContent();

        $this->getBreadcrumbLinks();

        $this->setTemplate('module:wpkcoloco/views/templates/front/pets.tpl');
    }

    public function getBreadcrumbLinks()
    {
        $breadcrumb = parent::getBreadcrumbLinks();
        $breadcrumb['links'][] = $this->addMyAccountToBreadcrumb();
        $breadcrumb['links'][] = [
            'title' => $this->trans('Pets', array(), 'Modules.Wpkcoloco.Pets'),
            'url' => $this->context->link->getModuleLink('wpkcoloco', 'Pets')
        ];

        return $breadcrumb;
    }
}